### ISSUE TITLE
BUG: text boxes don't validate

### ISSUE THREAD

**Issue by mckib2** [mogvaj/mogvaj.github.io#6]
Javascript is used to pull values from inputs before html5 input validation is run (typically on form submit).  I'm not sure how to force validation...

**Comment by mogvaj** [comment]
Can we go one input at a time.  Which one first?

**Comment by mckib2** [comment]
- Seed should be a number only?  Right now it's maked `type='text'`
- Timer is now a number input, but negative numbers are allowed because html5 validation is not run
